[package]
name = "mpvr"
version = "0.1.0"
edition = "2021"

[dependencies]
async-process = "2.3.0"
clap = { version = "4.5.32", features = ["derive"] }
mpvipc = "1.3.0"
sysinfo = "0.33.1"
tokio = { version = "1.44.1", features = ["full"] }
